[package]
name = "mathl"
version = "0.0.1"
authors = ["Samantha Enders <ladysamantha@protonmail.com>"]
description = "A math library for Rust. The goal is to use this with rhai"
license = "MIT"

[dependencies]
